# Generated by Django 3.2 on 2023-01-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.rubric', verbose_name='Rubric'),
        ),
    ]
