# Generated by Django 3.2 on 2023-01-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
    ]
