# Generated by Django 3.2 on 2023-01-31 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230131_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
