# Generated by Django 3.2 on 2023-02-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20230131_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
